---
# Playbook for creating OpenStack IDR VMs

# WARNING: Do not use set_facts in this role, since it'll create a hostvar
# on the host running the openstack client and not the VM created.
# This means multiple invocations of this role (for multiple VMs) will fail
# to work as expected since the hostvar is persistent across tasks.
# See defaults/main.yml for most of the logic.

# os_server may return a misleading error if the requested image is missing
# so run an explicit check
# https://github.com/ansible/ansible/issues/18921#issuecomment-268891980
# https://github.com/ansible/ansible/pull/19653

- name: idr vm | get image
  os_image_facts:
    image: "{{ idr_vm_image }}"
  check_mode: false
  # Creates variable openstack_image

- name: idr vm | check image
  fail:
    msg: "Openstack image {{ idr_vm_image }} not found"
  when: "not openstack_image"

- name: idr vm | create VM
  os_server:
    # Only add `-N` suffix for idr_vm_count>1
    name: "{{ idr_vm_name }}{{ (idr_vm_count > 1) | ternary('-' + item, '') }}"
    state: present
    image: "{{ idr_vm_image }}"
    key_name: "{{ idr_vm_keyname }}"
    flavor: "{{ idr_vm_flavour }}"
    nics: "{{ idr_vm_networks }}"
    auto_ip: "{{ idr_vm_assign_floating_ip }}"
    meta: >
      {{ dict([
          ("hostname", idr_vm_name),
          ("groups", ','.join(
            idr_vm_groups + idr_vm_cloud_group)),
          ("groups2", ','.join(idr_vm_extra_groups)),
        ] +
        idr_vm_ssh_metadata +
        idr_vm_network_metadata
      ) }}
    security_groups: "{{ idr_vm_security_groups | join(',') }}"
  register: vm
  with_sequence: "count={{ idr_vm_count }}"
